version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "georglauterbach"
      - "wernerfred"
    labels:
      - "area/ci"
      - "priority/low"
